# Add ~/bin to the path
export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH:./bin";

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

brew_prefix=""
if which brew &> /dev/null; then
	brew_prefix=$(brew --prefix)
fi

source ~/dotfiles/private/platform

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
for file in ~/dotfiles/shells/bash.d/{gitprompt,path,prompt,history,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Add tab completion for many Bash commands
brew_source "share/bash-completion/bash_completion"
if [ -z "$BASH_COMPLETION_COMPAT_DIR" ] && [ -f /etc/bash_completion ]; then
	source /etc/bash_completion;
fi;

brew_source "etc/bash_completion.d/git-completion.bash"
#brew_source "etc/bash_completion.d/git-prompt.sh"

# use this for commands and things that should only be local
if [ -e ~/.bash_local ]; then
	source ~/.bash_local
fi

source ~/perl5/perlbrew/etc/bashrc

CERT_PATH=$(python3 -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
