---
- hosts: all
  vars:
    home: "{{ lookup('env', 'HOME' }}"
    ansible_ssh_username: "{{ lookup('env','USER') }}"
    dotfile_repo_username: "{{ lookup('env','USER') }}"
    applications:
      - 1password
      - alfred
      - bettertouchtool
      - caffeine
      - dropbox
      - firefox
      - google-chrome
      - iterm2
      - keka
      - nvalt
      - skype
      - sublime-text
      - thunderbird
      - tunnelblick
      - vagrant
      - vagrant-manager
      - virtualbox
      - vlc
      - gpg-suite
      - adobe-creative-cloud
      - gas-mask
      - sourcetree
      - mysqlworkbench
      - rambox
      - slack
      - jetbrains-toolbox
      - moom
    brew_taps:
      - caskroom/cask
      - caskroom/versions
    brew_utils:
      - autoconf
      - autojump
      - bash
      - git
      - go
      - gpg
      - hub
      - mtr
      - openssl
      - ssh-copy-id
  tasks:
    - name: HOMEBREW | Install required Taps
      command: "/usr/local/bin/brew tap {{ item }}"
      with_items: "{{ brew_taps }}"

    - name: UTILS | Install
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_utils }}"

    - name: UTILS | Cleanup
      shell: /usr/local/bin/brew cleanup

    - name: CASKS | load list
      shell: /usr/local/bin/brew cask list | grep {{ item }}
      register: installed_applications
      with_items: "{{ applications }}"
      ignore_errors: true

    - set_fact:
        installed_applications: "{{ installed_applications.results|map(attribute='stdout') }}"

    - name: CASKS | install
      shell: /usr/local/bin/brew cask install {{ item }}
      with_items: "{{ applications }}"
      when: item not in installed_applications

#    - name: SETUP | system settings
#      script: setup/system_settings.sh
#      sudo: true
