#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# LESS!!!
#-------------------------------------------------------------------------------
# Pager and Editor
export PAGER="less"
export EDITOR="vim"
export VISUAL=$EDITOR
if [ "$UID" != 0 ]; then
    export XPAGER=$PAGER
    export XEDITOR="jedit"
fi

# less
export LESS="-MWi -x4 --shift 5"
export LESSHISTFILE="-"     # no less history file
if [ "$UID" != 0 ]; then
    export LESSCHARSET="utf-8"
    if [ -z "$LESSOPEN" ]; then
        if [ "$__distribution" = "Debian" ]; then
            [ -x "`which lesspipe`" ] && eval "$(lesspipe)"
        else
            [ -x "`which lesspipe.sh`" ] && export LESSOPEN="|lesspipe.sh %s"
        fi
    fi
    # Yep, 'less' can colorize manpages
    export LESS_TERMCAP_mb=$'\E[01;31m'
    export LESS_TERMCAP_md=$'\E[01;31m'
    export LESS_TERMCAP_me=$'\E[0m'
    export LESS_TERMCAP_se=$'\E[0m'
    export LESS_TERMCAP_so=$'\E[01;44;33m'
    export LESS_TERMCAP_ue=$'\E[0m'
    export LESS_TERMCAP_us=$'\E[01;32m'
fi