#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# History
#-------------------------------------------------------------------------------
# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace
HISTIGNORE="cd:ls:[bf]g:clear:exit"

# append to the history file, don't overwrite it
shopt -s histappend

PROMPT_COMMAND='history -a'
HISTTIMEFORMAT="%F %T "

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=99999
