#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Custom Prompt
#-------------------------------------------------------------------------------
# colors
RESTORE=$(echo -e '\033[0m')

RED='\[\033[00;31m\]'
GREEN='\[\033[00;32m\]'
YELLOW='\[\033[00;33m\]'
BLUE='\[\033[00;34m\]'
PURPLE='\[\033[00;35m\]'
CYAN='\[\033[00;36m\]'
LIGHTGRAY='\[\033[00;37m\]'

LRED=$(echo -e '\033[01;31m')
LGREEN=$(echo -e "\033[01;32m")
LYELLOW='\[\033[01;33m\]'
LBLUE=$(echo -e '\033[01;34m')
LPURPLE='\[\033[01;35m\]'
LCYAN='\[\033[01;36m\]'
WHITE='\[\033[01;37m\]'


# Select git info displayed, see /usr/lib/git-core/git-sh-prompt for more
export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1           # '*'=unstaged, '+'=staged
#export GIT_PS1_SHOWSTASHSTATE=1           # '$'=stashed
export GIT_PS1_SHOWUNTRACKEDFILES=1       # '%'=untracked
export GIT_PS1_SHOWUPSTREAM="verbose"     # 'u='=no difference, 'u+1'=ahead by 1 commit
export GIT_PS1_STATESEPARATOR=''          # No space between branch and index status
export GIT_PS1_DESCRIBE_STYLE="describe"  # detached HEAD style:

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color | xterm-256color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PROMPT_START='${debian_chroot:+($debian_chroot)}$(smiley) ${LGREEN}\u@\h${RESTORE}:'
    PROMPT_DIR='$LBLUE\w$RESTORE'
    PROMPT_END='\$ '
else
    PROMPT_START='${debian_chroot:+($debian_chroot)}$(smiley) \u@\h:'
    PROMPT_DIR='\w'
    PROMPT_END='\$ '
fi
PS1="${PROMPT_START}${PROMPT_DIR}${PROMPT_END}"
#unset color_prompt force_color_prompt

if [ -f "$brew_prefix/etc/bash_completion.d/git-completion.bash" ]; then
	export PROMPT_COMMAND='__git_ps1 "${VIRTUAL_ENV:+${LYELLOW}[`basename $VIRTUAL_ENV`]${RESTORE} }${PROMPT_START}${PROMPT_DIR}" "\$ "'
    #export PROMPT_COMMAND='__git_ps1 "${VIRTUAL_ENV:+[`basename $VIRTUAL_ENV`]}" '
    #export PS1='\u \w$(__git_ps1)\$ '
    #export PS1='${PROMPT_START}${PROMPT_DIR}$(__git_ps1 "(%s)")${PROMPT_END}'
else
__git_ps1() {
	$1
}
fi